---
- name: PHP and PHP Extensions
  sudo: yes
  apt: name={{ item }} state=present
  with_items:
    - php
    - php-cli
    - php-fpm
    - php-mysql
    - php-xml
    - php-mbstring
    - php-tokenizer
    - php-zip

# - include: composer.yml
